channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.5.1
  - samtools=1.3
  - snakemake=3.8.2
  - pyyaml=3.11
  - bwa=0.7.8
  - picard=2.9.2
  - trimmomatic=0.36
  - bowtie2=2.3.2




