---
workdir:  "scratch/"
threads:   10
fastqdir:  "/home/mgalland/data/01_sequencing_runs/2014_7accessions/raw/"
resultdir: "results/"

samples:
  LA1777:
    forward:  "LA1777_GCCAAT_L008_R1_001.fastq.gz"
    reverse:  "LA1777_GCCAAT_L008_R2_001.fastq.gz"
  PI127826:
    forward:  "PI127826_CGATGT_L008_R1_001.fastq.gz"
    reverse:  "PI127826_CGATGT_L008_R2_001.fastq.gz"
  F1:
    forward:  "F1cross_TGACCA_L008_R1_001.fastq.gz"
    reverse:  "F1cross_TGACCA_L008_R1_001.fastq.gz"

adapters: "/zfs/datastore0/software/src/Trimmomatic-0.30/adapters/TruSeq3-PE.fa"
 
## Genomic references, annotations and aligner indexes
refs:
  genome:  "/home/mgalland/data/02_refs/Solanum_lycopersicum/ITAG3.0/S_lycopersicum_chromosomes.3.00.fa"
  gff:     "/home/mgalland/data/02_refs/Solanum_lycopersicum/ITAG3.0/ITAG3.0_gene_models.gff"
  gtf:     "/home/mgalland/data/02_refs/Solanum_lycopersicum/ITAG3.0/ITAG3.0_gene_models.gtf"
  star:    "/home/mgalland/data/02_refs/Solanum_lycopersicum/ITAG3.0/star_genome/"
  bowtie:  "/home/mgalland/data/02_refs/Solanum_lycopersicum/ITAG3.0/bowtie_index/S_lycopersicum_chromosomes.3.00.fa"
  chromsizes: "/home/mgalland/data/02_refs/Solanum_lycopersicum/ITAG3.0/chromSizes.txt"

# trimmomatic
trimmomatic:
  adapters: "/zfs/datastore0/software/src/Trimmomatic-0.36/adapters/TruSeq3-PE.fa"
  jarfile: "/zfs/datastore0/software/src/Trimmomatic-0.36/trimmomatic-0.36.jar"
  seedMisMatches: '2'
  palindromeClipTreshold: '30'
  simpleClipThreshold: '10'
  LeadMinTrimQual: '3'
  TrailMinTrimQual: '3'
  windowSize: '4'
  avgMinQual: '15'
  minReadLength: '40'
  phred: "-phred33" # phred: for illumina >1.8 the quality score are encoded by phred33

# Parameters for STAR
# RPM = read raw count / total number of uniquely mapping reads *10⁶  (for ".Unique." signal files)
# RPM = read raw count / total number of unique and multiple mapping reads (for ".UniqueMultiple." signal files)
star:
  samtype: 'BAM SortedByCoordinate' # type of output
  outwigtype: 'bedGraph' # wig type 
  outwigstrand: 'Stranded' # strandness of wig file 
  outwignorm: 'RPM' # These RPM normalizations are used by the ENCODE consortium. 
  mismatches: '2' # alignment will be output only if it has less mismatches than this number
  unmapped: 'Fastx' # unmapped accepted values are None or Fastx (to output fastq files of unmapped reads)
  multimappers: '10' # maximum number of loci the read is allowed to map to
  matchminoverlengthread: '0.66' # alignment will be output if percentage of read length is higher than this value (66% of 2x100bp = 132 nucleotides)	


