---
workdir:  "/zfs/scratch/mgalland_temp/freebayes/"
fastqdir: "/home/mgalland/data/01_sequencing_runs/20170718_Hartwig/"
resultdir: "results/"

# units to samples tsv file
units: "units.tsv"
#samples:
#    test:
#      lib_forward:
##        L1: "test_L1_R1.fastq.gz"
#        L2: "test_L2_R1.fastq.gz"
#      lib_reverse:
#        L1: "test_L1_R2.fastq.gz"
#        L2: "test_L2_R2.fastq.gz"
#  LA1777:
#    lib_forward:
#      L1: "LA1777_HJL5GALXX_S1_L001_R1_001.fastq.gz"
#      L2: "LA1777_HJL5GALXX_S1_L002_R1_001.fastq.gz"
#      L3: "LA1777_HJL5GALXX_S1_L003_R1_001.fastq.gz"
#      L4: "LA1777_HJL5GALXX_S1_L004_R1_001.fastq.gz"
#      L5: "LA1777_HJL5GALXX_S1_L005_R1_001.fastq.gz"
#      L6: "LA1777_HJL5GALXX_S1_L006_R1_001.fastq.gz"
#      L7: "LA1777_HJL5GALXX_S1_L007_R1_001.fastq.gz"
#      L8: "LA1777_HJL5GALXX_S1_L008_R1_001.fastq.gz"
#    lib_reverse:
#      L1: "LA1777_HJL5GALXX_S1_L001_R2_001.fastq.gz"
#      L2: "LA1777_HJL5GALXX_S1_L002_R2_001.fastq.gz"
#      L3: "LA1777_HJL5GALXX_S1_L003_R2_001.fastq.gz"
#      L4: "LA1777_HJL5GALXX_S1_L004_R2_001.fastq.gz"
 #     L5: "LA1777_HJL5GALXX_S1_L005_R2_001.fastq.gz"
 #     L6: "LA1777_HJL5GALXX_S1_L006_R2_001.fastq.gz"
 #     L7: "LA1777_HJL5GALXX_S1_L007_R2_001.fastq.gz"
 #     L8: "LA1777_HJL5GALXX_S1_L008_R2_001.fastq.gz"
        
adapters: "adapters.fasta"
 
## Genomic references, annotations and aligner indexes
refs:
  genome:  "/home/mgalland/data/02_refs/Solanum_lycopersicum/ITAG3.0/S_lycopersicum_chromosomes.3.00.fa"
  gff:     "/home/mgalland/data/02_refs/Solanum_lycopersicum/ITAG3.2/ITAG3.2_gene_models.gff"
  gtf:     "/home/mgalland/data/02_refs/Solanum_lycopersicum/ITAG3.0/ITAG3.0_gene_models.gtf"
  star:    "/home/mgalland/data/02_refs/Solanum_lycopersicum/ITAG3.0/star_genome/"
  bowtie:  "/home/mgalland/data/02_refs/Solanum_lycopersicum/ITAG3.0/bowtie_index/S_lycopersicum_chromosomes.3.00.fa"
  chromsizes: "/home/mgalland/data/02_refs/Solanum_lycopersicum/ITAG3.0/chromSizes.txt" # for bedgraph to bigwig conversion

# trimmomatic
trimmomatic:
  adapters: "/zfs/datastore0/software/src/Trimmomatic-0.36/adapters/TruSeq3-PE.fa"
  seedMisMatches: '2'
  palindromeClipTreshold: '30'
  simpleClipThreshold: '10'
  LeadMinTrimQual: '3'
  TrailMinTrimQual: '3'
  windowSize: '4'
  avgMinQual: '15'
  minReadLength: '40'
  phred: "-phred33" # phred: for illumina >1.8 the quality score are encoded by phred33

# STAR aligner
# RPM = read raw count / total number of uniquely mapping reads *10⁶  (for ".Unique." signal files)
# RPM = read raw count / total number of unique and multiple mapping reads (for ".UniqueMultiple." signal files)
star:
  samtype: 'BAM SortedByCoordinate' # type of output
  outwigtype: 'wiggle' # wig type 
  outwigstrand: 'Unstranded' # strandness of wig file ('Stranded' or 'Unstranded')
  outwignorm: 'RPM' # These RPM normalizations are used by the ENCODE consortium. 
  mismatches: '2' # alignment will be output only if it has less mismatches than this number
  unmapped: 'None' # unmapped accepted values are None or Fastx (to output fastq files of unmapped reads)
  multimappers: '10' # maximum number of loci the read is allowed to map to
  matchminoverlengthread: '0.66' # alignment will be output if percentage of read length is higher than this value (66% of 2x100bp = 132 nucleotides)	
  intronmax: '25000' # max intron in tomato genome is 22,729
  matesgap: '20000'  # max length between mates 
  genomeload: 'NoSharedMemory' # see STAR manual (LoadAndKeep, LoadAndRemove, LoadAndExit, Remove, NoSharedMemory (default)
  genomeram: '200000000000' # 100Gb RAM to generate genome
  samattributes: 'NH HI AS nM MD' # SAM attributes (by default only NH HI AS nM). See STAR manual


