channels:
  - defaults
  - bioconda
  - r
  - conda-forge
dependencies:
  - python=3.5.1
  - picard = 2.14
  - samtools=1.3.1
  - snakemake=3.8.2
  - pyyaml=3.11
  - bwa = 0.7.8
  - trimmomatic=0.36
  - fastqc = 0.11.6
  - freebayes = 1.1.0
  - vcflib = 1.0.0_rc1

