channels:
  - defaults
  - bioconda
  - r
  - conda-forge
dependencies:
  - python = 3.5
  - samtools=1.3.1
  - snakemake=3.8.2
  - trimmomatic=0.36
  - fastqc=0.11.6
  - trinity=2.4.0
  - pandas=0.22.0
  - picard=2.9.2
  - biopython=1.68



