channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.5.1
  - samtools=1.3.1
  - snakemake=3.8.2
  - pyyaml=3.11
  - star=2.4.0h1
  - subread=1.5.0p3
  - bowtie2=2.1.0
  - picard=1.97


